apiVersion: batch/v2alpha1
kind: CronJob

metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.name }}

# CronJob spec
spec:
  # Every 20 minutes
  schedule: "5,15,25,35,45,55 5-20 * * MON-FRI"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  
  # Job template spec
  jobTemplate:

    # Job Spec
    spec:
      # Maximum runtime: 10 minutes
      activeDeadlineSeconds: 600
      backoffLimit: 10
      completions: 1
      parallelism: 1
      ttlSecondsAfterFinished: 3600

      template:
        metadata:
          name: {{ .Values.name }}
          labels:
            app: {{ .Values.name }}

        # Pod spec
        spec:
          ttlSecondsAfterFinished: 3600
          containers:
            - name: {{ .Values.image.name }}
              # This image is supposed to be publicly accessible
              image: quay.io/giantswarm/{{ .Values.image.name }}:{{ .Values.image.sha }}
              env:
                - name: ELASTICSEARCH_ENDPOINT
                  value: http://sitesearch-app:9200/
                - name: REPOSITORY_BRANCH
                  value: master
                - name: REPOSITORY_SUBFOLDER
                  value: src/content
                - name: APIDOCS_BASE_URI
                  value: https://docs.giantswarm.io/api/
                - name: APIDOCS_BASE_PATH
                  value: /api/
                - name: API_SPEC_FILES
                  value: yaml/spec.yaml,yaml/definitions.yaml,yaml/parameters.yaml,yaml/responses.yaml
              volumeMounts:
                - name: cache
                  mountPath: /home/indexer/gitcache
              resources:
                requests:
                  cpu: 100m
                  memory: 100M
                limits:
                  cpu: 100m
                  memory: 100M
          volumes:
            - name: cache
              emptyDir: {}
          restartPolicy: OnFailure
          serviceAccount: {{ .Values.name }}
          serviceAccountName: {{ .Values.name }}
