---
# Indexer cronjob for docs, api-spec
apiVersion: batch/v1
kind: CronJob

metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.name }}-docs

# CronJob spec
spec:
  # Every 20 minutes
  schedule: "5,15,25,35,45,55 5-20 * * MON-FRI"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  securityContext:
    seccompProfile:
      type: RuntimeDefault

  # Job template spec
  jobTemplate:

    # Job Spec
    spec:
      # Maximum runtime: 10 minutes
      activeDeadlineSeconds: 600
      backoffLimit: 10
      completions: 1
      parallelism: 1
      ttlSecondsAfterFinished: 600

      template:
        metadata:
          name: {{ .Values.name }}-docs
          labels:
            app: {{ .Values.name }}
            observability.giantswarm.io/tenant: giantswarm

        # Pod spec
        spec:
          containers:
            - name: {{ .Values.image.name }}
              args: ["hugo"]
              # This image is supposed to be publicly accessible
              image: {{ .Values.image.registry }}/giantswarm/{{ .Values.image.name }}:{{ .Values.image.tag }}
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
                runAsNonRoot: true
                seccompProfile:
                  type: RuntimeDefault
              env:
                - name: OPENSEARCH_ENDPOINT
                  value: {{ .Values.opensearchEndpoint }}
                - name: BASE_URL
                  value: https://docs.giantswarm.io
                - name: REPOSITORY_HANDLE
                  value: giantswarm/docs
                - name: REPOSITORY_BRANCH
                  value: main
                - name: REPOSITORY_SUBFOLDER
                  value: src/content
                - name: INDEX_NAME
                  value: docs
                - name: TYPE_LABEL
                  value: Documentation
              volumeMounts:
                - name: docs-cache
                  mountPath: /home/indexer/gitcache
              resources:
                requests:
                  cpu: {{ .Values.resources.requests.cpu }}
                  memory: {{ .Values.resources.requests.memory }}
                limits:
                  cpu: {{ .Values.resources.limits.cpu }}
                  memory: {{ .Values.resources.limits.memory }}
          volumes:
            - name: docs-cache
              emptyDir: {}
          restartPolicy: OnFailure
          serviceAccount: {{ .Values.name }}
          serviceAccountName: {{ .Values.name }}
