---
# Indexer cronjob for docs, api-spec
apiVersion: batch/v2alpha1
kind: CronJob

metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.name }}-docs

# CronJob spec
spec:
  # Every 20 minutes
  schedule: "5,15,25,35,45,55 5-20 * * MON-FRI"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  
  # Job template spec
  jobTemplate:

    # Job Spec
    spec:
      # Maximum runtime: 10 minutes
      activeDeadlineSeconds: 600
      backoffLimit: 10
      completions: 1
      parallelism: 1
      ttlSecondsAfterFinished: 3600

      template:
        metadata:
          name: {{ .Values.name }}-docs
          labels:
            app: {{ .Values.name }}

        # Pod spec
        spec:
          ttlSecondsAfterFinished: 3600
          containers:
            - name: {{ .Values.image.name }}
              args: ["docs"]
              # This image is supposed to be publicly accessible
              image: quay.io/giantswarm/{{ .Values.image.name }}:{{ .Values.image.sha }}
              env:
                - name: ELASTICSEARCH_ENDPOINT
                  value: {{ .Values.elasticsearchEndpoint }}
              volumeMounts:
                - name: cache
                  mountPath: /home/indexer/gitcache
              resources:
                requests:
                  cpu: 100m
                  memory: 100M
                limits:
                  cpu: 100m
                  memory: 100M
          volumes:
            - name: cache
              emptyDir: {}
          restartPolicy: OnFailure
          serviceAccount: {{ .Values.name }}
          serviceAccountName: {{ .Values.name }}
---
# Indexer cronjob for blog posts
apiVersion: batch/v2alpha1
kind: CronJob

metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.name }}-blog

spec:
  # Once a day on workdays at 08:51
  schedule: "51 8 * * MON-FRI"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  
  jobTemplate:
    # Job Spec
    spec:
      # Maximum runtime: 10 minutes
      activeDeadlineSeconds: 600
      backoffLimit: 10
      completions: 1
      parallelism: 1
      ttlSecondsAfterFinished: 3600

      template:
        metadata:
          name: {{ .Values.name }}-blog
          labels:
            app: {{ .Values.name }}

        # Pod spec
        spec:
          ttlSecondsAfterFinished: 3600
          containers:
            - name: {{ .Values.image.name }}
              args: ["docs"]
              # This image is supposed to be publicly accessible
              image: quay.io/giantswarm/{{ .Values.image.name }}:{{ .Values.image.sha }}
              env:
                - name: ELASTICSEARCH_ENDPOINT
                  value: {{ .Values.elasticsearchEndpoint }}
                - name: HUBSPOT_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: hubspot-api-key
                      key: hubspot-api-key
              resources:
                requests:
                  cpu: 100m
                  memory: 100M
                limits:
                  cpu: 100m
                  memory: 100M
          restartPolicy: OnFailure
          serviceAccount: {{ .Values.name }}
          serviceAccountName: {{ .Values.name }}
