---
# Indexer cronjob for blog posts
apiVersion: batch/v1
kind: CronJob

metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.name }}-blog

spec:
  # Once a day on workdays at 08:51
  schedule: "51 8 * * MON-FRI"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  securityContext:
    seccompProfile:
      type: RuntimeDefault

  jobTemplate:
    # Job Spec
    spec:
      # Maximum runtime: 10 minutes
      activeDeadlineSeconds: 600
      backoffLimit: 10
      completions: 1
      parallelism: 1
      ttlSecondsAfterFinished: 600

      template:
        metadata:
          name: {{ .Values.name }}-blog
          labels:
            app: {{ .Values.name }}
            observability.giantswarm.io/tenant: giantswarm

        # Pod spec
        spec:
          containers:
            - name: {{ .Values.image.name }}
              args: ["blog"]
              # This image is supposed to be publicly accessible
              image: {{ .Values.image.registry }}/giantswarm/{{ .Values.image.name }}:{{ .Values.image.tag }}
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
                runAsNonRoot: true
                seccompProfile:
                  type: RuntimeDefault
              env:
                - name: OPENSEARCH_ENDPOINT
                  value: {{ .Values.opensearchEndpoint }}
                - name: HUBSPOT_ACCESS_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.name }}-credentials
                      key: hubspot-access-token
                - name: BASE_URL
                  value: https://www.giantswarm.io/blog
              resources:
                requests:
                  cpu: {{ .Values.resources.requests.cpu }}
                  memory: {{ .Values.resources.requests.memory }}
                limits:
                  cpu: {{ .Values.resources.limits.cpu }}
                  memory: {{ .Values.resources.limits.memory }}
          restartPolicy: OnFailure
          serviceAccount: {{ .Values.name }}
          serviceAccountName: {{ .Values.name }}
