---
# Indexer cronjob for docs, api-spec
apiVersion: batch/v1
kind: CronJob

metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.name }}-docs

# CronJob spec
spec:
  # Every 20 minutes
  schedule: "5,15,25,35,45,55 5-20 * * MON-FRI"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  
  # Job template spec
  jobTemplate:

    # Job Spec
    spec:
      # Maximum runtime: 10 minutes
      activeDeadlineSeconds: 600
      backoffLimit: 10
      completions: 1
      parallelism: 1
      ttlSecondsAfterFinished: 600

      template:
        metadata:
          name: {{ .Values.name }}-docs
          labels:
            app: {{ .Values.name }}

        # Pod spec
        spec:
          containers:
            - name: {{ .Values.image.name }}
              args: ["hugo"]
              # This image is supposed to be publicly accessible
              image: quay.io/giantswarm/{{ .Values.image.name }}:{{ .Values.image.tag }}
              env:
                - name: ELASTICSEARCH_ENDPOINT
                  value: {{ .Values.elasticsearchEndpoint }}
                - name: BASE_URL
                  value: https://docs.giantswarm.io/
                - name: REPOSITORY_HANDLE
                  value: giantswarm/docs
                - name: REPOSITORY_BRANCH
                  value: main
                - name: REPOSITORY_SUBFOLDER
                  value: src/content
                - name: INDEX_NAME
                  value: docs
              volumeMounts:
                - name: docs-cache
                  mountPath: /home/indexer/gitcache
              resources:
                requests:
                  cpu: 200m
                  memory: 50M
                limits:
                  cpu: 1000m
                  memory: 500M
          volumes:
            - name: docs-cache
              emptyDir: {}
          restartPolicy: OnFailure
          serviceAccount: {{ .Values.name }}
          serviceAccountName: {{ .Values.name }}
