---
# Indexer cronjob for intranet content
apiVersion: batch/v1
kind: CronJob

metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.name }}-intranet

spec:
  # Every 10 minutes
  schedule: "*/10 5-20 * * MON-FRI"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  
  jobTemplate:
    # Job Spec
    spec:
      # Maximum runtime: 10 minutes
      activeDeadlineSeconds: 600
      backoffLimit: 10
      completions: 1
      parallelism: 1
      ttlSecondsAfterFinished: 600

      template:
        metadata:
          name: {{ .Values.name }}-intranet
          labels:
            app: {{ .Values.name }}

        # Pod spec
        spec:
          containers:
            - name: {{ .Values.image.name }}
              args: ["hugo"]
              # This image is supposed to be publicly accessible
              image: quay.io/giantswarm/{{ .Values.image.name }}:{{ .Values.image.tag }}
              env:
                - name: ELASTICSEARCH_ENDPOINT
                  value: {{ .Values.elasticsearchEndpoint }}
                - name: BASE_URL
                  value: https://intranet.giantswarm.io
                - name: GITHUB_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: github-access-token
                      key: github-access-token
                - name: REPOSITORY_HANDLE
                  value: giantswarm/giantswarm
                - name: REPOSITORY_BRANCH
                  value: main
                - name: REPOSITORY_SUBFOLDER
                  value: content/docs
                - name: INDEX_NAME
                  value: intranet
              volumeMounts:
                - name: intranet-cache
                  mountPath: /home/indexer/gitcache
              resources:
                requests:
                  cpu: 200m
                  memory: 50M
                limits:
                  cpu: 1000m
                  memory: 500M
          volumes:
            - name: intranet-cache
              emptyDir: {}
          restartPolicy: OnFailure
          serviceAccount: {{ .Values.name }}
          serviceAccountName: {{ .Values.name }}
