---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ .Values.name }}
  name: {{ .Values.name }}-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  github-access-token: {{ .Values.credentials.githubAccessToken | b64enc }}
  hubspot-access-token: {{ .Values.credentials.hubspotAccessToken | b64enc }}
  opensearch-user-name: {{ .Values.credentials.opensearchUsername | b64enc }}
  opensearch-password: {{ .Values.credentials.opensearchPassword | b64enc }}
