name: Full test

on:
  # manual only
  workflow_dispatch: {}
  push:
    branches:
      - integration-testing

jobs:
  test:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Clone source repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Build docker image
        run: make image
      - name: Execute test
        env:
          HUBSPOT_ACCESS_TOKEN: ${{ secrets.HUBSPOT_ACCESS_TOKEN }}
        run: |
          touch .env
          make int-test
